// Generated by gencpp from file ypspur_ros/DigitalInput.msg
// DO NOT EDIT!


#ifndef YPSPUR_ROS_MESSAGE_DIGITALINPUT_H
#define YPSPUR_ROS_MESSAGE_DIGITALINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ypspur_ros
{
template <class ContainerAllocator>
struct DigitalInput_
{
  typedef DigitalInput_<ContainerAllocator> Type;

  DigitalInput_()
    : header()
    , name()
    , state()  {
    }
  DigitalInput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ypspur_ros::DigitalInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ypspur_ros::DigitalInput_<ContainerAllocator> const> ConstPtr;

}; // struct DigitalInput_

typedef ::ypspur_ros::DigitalInput_<std::allocator<void> > DigitalInput;

typedef boost::shared_ptr< ::ypspur_ros::DigitalInput > DigitalInputPtr;
typedef boost::shared_ptr< ::ypspur_ros::DigitalInput const> DigitalInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ypspur_ros::DigitalInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ypspur_ros::DigitalInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ypspur_ros::DigitalInput_<ContainerAllocator1> & lhs, const ::ypspur_ros::DigitalInput_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ypspur_ros::DigitalInput_<ContainerAllocator1> & lhs, const ::ypspur_ros::DigitalInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ypspur_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ypspur_ros::DigitalInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ypspur_ros::DigitalInput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ypspur_ros::DigitalInput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "678afd95d51d5a66befdfa88bb0ec5d9";
  }

  static const char* value(const ::ypspur_ros::DigitalInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x678afd95d51d5a66ULL;
  static const uint64_t static_value2 = 0xbefdfa88bb0ec5d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ypspur_ros/DigitalInput";
  }

  static const char* value(const ::ypspur_ros::DigitalInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string[] name\n"
"bool[] state\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ypspur_ros::DigitalInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DigitalInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ypspur_ros::DigitalInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ypspur_ros::DigitalInput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YPSPUR_ROS_MESSAGE_DIGITALINPUT_H
