// Generated by gencpp from file ypspur_ros/JointPositionControl.msg
// DO NOT EDIT!


#ifndef YPSPUR_ROS_MESSAGE_JOINTPOSITIONCONTROL_H
#define YPSPUR_ROS_MESSAGE_JOINTPOSITIONCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ypspur_ros
{
template <class ContainerAllocator>
struct JointPositionControl_
{
  typedef JointPositionControl_<ContainerAllocator> Type;

  JointPositionControl_()
    : header()
    , joint_names()
    , positions()
    , velocities()
    , accelerations()  {
    }
  JointPositionControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joint_names(_alloc)
    , positions(_alloc)
    , velocities(_alloc)
    , accelerations(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _positions_type;
  _positions_type positions;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocities_type;
  _velocities_type velocities;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _accelerations_type;
  _accelerations_type accelerations;





  typedef boost::shared_ptr< ::ypspur_ros::JointPositionControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ypspur_ros::JointPositionControl_<ContainerAllocator> const> ConstPtr;

}; // struct JointPositionControl_

typedef ::ypspur_ros::JointPositionControl_<std::allocator<void> > JointPositionControl;

typedef boost::shared_ptr< ::ypspur_ros::JointPositionControl > JointPositionControlPtr;
typedef boost::shared_ptr< ::ypspur_ros::JointPositionControl const> JointPositionControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ypspur_ros::JointPositionControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ypspur_ros::JointPositionControl_<ContainerAllocator1> & lhs, const ::ypspur_ros::JointPositionControl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.joint_names == rhs.joint_names &&
    lhs.positions == rhs.positions &&
    lhs.velocities == rhs.velocities &&
    lhs.accelerations == rhs.accelerations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ypspur_ros::JointPositionControl_<ContainerAllocator1> & lhs, const ::ypspur_ros::JointPositionControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ypspur_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ypspur_ros::JointPositionControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ypspur_ros::JointPositionControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ypspur_ros::JointPositionControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ff21d2400d71a236d035d99166b594d";
  }

  static const char* value(const ::ypspur_ros::JointPositionControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ff21d2400d71a23ULL;
  static const uint64_t static_value2 = 0x6d035d99166b594dULL;
};

template<class ContainerAllocator>
struct DataType< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ypspur_ros/JointPositionControl";
  }

  static const char* value(const ::ypspur_ros::JointPositionControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string[] joint_names\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ypspur_ros::JointPositionControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joint_names);
      stream.next(m.positions);
      stream.next(m.velocities);
      stream.next(m.accelerations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPositionControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ypspur_ros::JointPositionControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ypspur_ros::JointPositionControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocities[i]);
    }
    s << indent << "accelerations[]" << std::endl;
    for (size_t i = 0; i < v.accelerations.size(); ++i)
    {
      s << indent << "  accelerations[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.accelerations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YPSPUR_ROS_MESSAGE_JOINTPOSITIONCONTROL_H
