// Generated by gencpp from file cirkit_waypoint_manager_msgs/WaypointArray.msg
// DO NOT EDIT!


#ifndef CIRKIT_WAYPOINT_MANAGER_MSGS_MESSAGE_WAYPOINTARRAY_H
#define CIRKIT_WAYPOINT_MANAGER_MSGS_MESSAGE_WAYPOINTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cirkit_waypoint_manager_msgs/Waypoint.h>

namespace cirkit_waypoint_manager_msgs
{
template <class ContainerAllocator>
struct WaypointArray_
{
  typedef WaypointArray_<ContainerAllocator> Type;

  WaypointArray_()
    : header()
    , waypoints()  {
    }
  WaypointArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointArray_

typedef ::cirkit_waypoint_manager_msgs::WaypointArray_<std::allocator<void> > WaypointArray;

typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::WaypointArray > WaypointArrayPtr;
typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::WaypointArray const> WaypointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator1> & lhs, const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator1> & lhs, const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cirkit_waypoint_manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33b4e9bd7ee512ebf01678e5b04340d6";
  }

  static const char* value(const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33b4e9bd7ee512ebULL;
  static const uint64_t static_value2 = 0xf01678e5b04340d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cirkit_waypoint_manager_msgs/WaypointArray";
  }

  static const char* value(const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Waypoint[] waypoints\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cirkit_waypoint_manager_msgs/Waypoint\n"
"Header header\n"
"int32 number\n"
"geometry_msgs/Pose pose\n"
"int32 is_search_area\n"
"float64 reach_tolerance\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cirkit_waypoint_manager_msgs::WaypointArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CIRKIT_WAYPOINT_MANAGER_MSGS_MESSAGE_WAYPOINTARRAY_H
