// Generated by gencpp from file cirkit_waypoint_manager_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef CIRKIT_WAYPOINT_MANAGER_MSGS_MESSAGE_WAYPOINT_H
#define CIRKIT_WAYPOINT_MANAGER_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace cirkit_waypoint_manager_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : header()
    , number(0)
    , pose()
    , is_search_area(0)
    , reach_tolerance(0.0)  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , number(0)
    , pose(_alloc)
    , is_search_area(0)
    , reach_tolerance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _number_type;
  _number_type number;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef int32_t _is_search_area_type;
  _is_search_area_type is_search_area;

   typedef double _reach_tolerance_type;
  _reach_tolerance_type reach_tolerance;





  typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::cirkit_waypoint_manager_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::cirkit_waypoint_manager_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.number == rhs.number &&
    lhs.pose == rhs.pose &&
    lhs.is_search_area == rhs.is_search_area &&
    lhs.reach_tolerance == rhs.reach_tolerance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cirkit_waypoint_manager_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "522a0978e774a47933c16d3e9d0fcf91";
  }

  static const char* value(const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x522a0978e774a479ULL;
  static const uint64_t static_value2 = 0x33c16d3e9d0fcf91ULL;
};

template<class ContainerAllocator>
struct DataType< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cirkit_waypoint_manager_msgs/Waypoint";
  }

  static const char* value(const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 number\n"
"geometry_msgs/Pose pose\n"
"int32 is_search_area\n"
"float64 reach_tolerance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.number);
      stream.next(m.pose);
      stream.next(m.is_search_area);
      stream.next(m.reach_tolerance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cirkit_waypoint_manager_msgs::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "is_search_area: ";
    Printer<int32_t>::stream(s, indent + "  ", v.is_search_area);
    s << indent << "reach_tolerance: ";
    Printer<double>::stream(s, indent + "  ", v.reach_tolerance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CIRKIT_WAYPOINT_MANAGER_MSGS_MESSAGE_WAYPOINT_H
