// Generated by gencpp from file cirkit_waypoint_navigator/TeleportAbsoluteRequest.msg
// DO NOT EDIT!


#ifndef CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTEREQUEST_H
#define CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cirkit_waypoint_navigator
{
template <class ContainerAllocator>
struct TeleportAbsoluteRequest_
{
  typedef TeleportAbsoluteRequest_<ContainerAllocator> Type;

  TeleportAbsoluteRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  TeleportAbsoluteRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TeleportAbsoluteRequest_

typedef ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<std::allocator<void> > TeleportAbsoluteRequest;

typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest > TeleportAbsoluteRequestPtr;
typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest const> TeleportAbsoluteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator1> & lhs, const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator1> & lhs, const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cirkit_waypoint_navigator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa130bc60ee651385ULL;
  static const uint64_t static_value2 = 0x5dc62ea83fcc5b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cirkit_waypoint_navigator/TeleportAbsoluteRequest";
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
;
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleportAbsoluteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTEREQUEST_H
