// Generated by gencpp from file cirkit_waypoint_navigator/TeleportAbsoluteResponse.msg
// DO NOT EDIT!


#ifndef CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTERESPONSE_H
#define CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cirkit_waypoint_navigator
{
template <class ContainerAllocator>
struct TeleportAbsoluteResponse_
{
  typedef TeleportAbsoluteResponse_<ContainerAllocator> Type;

  TeleportAbsoluteResponse_()
    {
    }
  TeleportAbsoluteResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TeleportAbsoluteResponse_

typedef ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<std::allocator<void> > TeleportAbsoluteResponse;

typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse > TeleportAbsoluteResponsePtr;
typedef boost::shared_ptr< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse const> TeleportAbsoluteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cirkit_waypoint_navigator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cirkit_waypoint_navigator/TeleportAbsoluteResponse";
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleportAbsoluteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cirkit_waypoint_navigator::TeleportAbsoluteResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTERESPONSE_H
