// Generated by gencpp from file cirkit_waypoint_navigator/TeleportAbsolute.msg
// DO NOT EDIT!


#ifndef CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTE_H
#define CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTE_H

#include <ros/service_traits.h>


#include <cirkit_waypoint_navigator/TeleportAbsoluteRequest.h>
#include <cirkit_waypoint_navigator/TeleportAbsoluteResponse.h>


namespace cirkit_waypoint_navigator
{

struct TeleportAbsolute
{

typedef TeleportAbsoluteRequest Request;
typedef TeleportAbsoluteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportAbsolute
} // namespace cirkit_waypoint_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsolute > {
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsolute&) { return value(); }
};

template<>
struct DataType< ::cirkit_waypoint_navigator::TeleportAbsolute > {
  static const char* value()
  {
    return "cirkit_waypoint_navigator/TeleportAbsolute";
  }

  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsolute&) { return value(); }
};


// service_traits::MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest> should match
// service_traits::MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsolute >
template<>
struct MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsolute >::value();
  }
  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest> should match
// service_traits::DataType< ::cirkit_waypoint_navigator::TeleportAbsolute >
template<>
struct DataType< ::cirkit_waypoint_navigator::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return DataType< ::cirkit_waypoint_navigator::TeleportAbsolute >::value();
  }
  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse> should match
// service_traits::MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsolute >
template<>
struct MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cirkit_waypoint_navigator::TeleportAbsolute >::value();
  }
  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse> should match
// service_traits::DataType< ::cirkit_waypoint_navigator::TeleportAbsolute >
template<>
struct DataType< ::cirkit_waypoint_navigator::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return DataType< ::cirkit_waypoint_navigator::TeleportAbsolute >::value();
  }
  static const char* value(const ::cirkit_waypoint_navigator::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CIRKIT_WAYPOINT_NAVIGATOR_MESSAGE_TELEPORTABSOLUTE_H
